# Generated by Django 5.2.8 on 2025-11-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='img_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='example-title', max_length=100),
            preserve_default=False,
        ),
    ]
