# Generated by Django 5.2.8 on 2025-11-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutus_img_url_aboutus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='img_url',
            field=models.URLField(default='example-title'),
            preserve_default=False,
        ),
    ]
